### ISSUE TITLE
"Error defining property 'server_socket' of class 'JS_Server'" when launching Simulator_App

### ISSUE THREAD

**Issue by lindseyerionbarner** [adamcohenlab/luminos-microscopy#1]
Hi there, I have been working on installing this software and was able to launch the simulator before successfully installing all necessary files for integrating a Hamamatsu Orca Fusion camera. I am able to run Example_app(); and view the live feed from the camera, but after doing the camera installation the simulator no longer able to run stably (I am hoping to run the simulator as part of the instructions to customize the user interface). I'm not sure if the camera installation is related or if something else is going on.

I get the following error about 5 seconds after the simulator launches:

"Error using Simulator_App (line 7)
Error defining property 'server_socket' of class 'JS_Server'. Class named 'tcpserver.internal.TCPServer' is
undefined or does not support property validation." If you are able to provide any clues as to where this is coming from or which file I should troubleshoot, that would be great! Thank you!

**Comment by rhotter** [comment]
Hi! Happy to help – what version of MATLAB are you using?

**Comment by lindseyerionbarner** [comment]
Thank you very much for your help! I am using Matlab R2020b.

**Comment by rhotter** [comment]
Ah, Luminos is not compatible with versions of MATLAB earlier than 2021a. tcpserver was only introduced in 2021a, so that is why you are getting the error. I would recommend upgrading to the latest version of MATLAB.

**Comment by lindseyerionbarner** [comment]
Awesome, thank you! That fixed the issue.
