### ISSUE TITLE
Change user's name in Getting Started

### ISSUE THREAD

**Issue by Luorong37** [adamcohenlab/luminos-microscopy#3]
Hi Cohen Lab
I'm a student in Peng Zou‘s lab. We are bulding a new microscope for slicing imaging, and are honored to use your program.
When i run `app = Simulator_App();`  in the last step of getting started, it shows error with your users name. i thought i should change it some where but i can't find it. <Example.json> has tried but nothing happenned.
Thanks for reply!

>  app = Simulator_App();

> 错误使用 mkdir
拒绝访问。
出错 Rig_Control_App/loadInitData (第 219 行)
                        mkdir(app.Rig_Init.dataDirectory);

-----------------or

>错误使用 Rig_Control_App/loadInitData
Directory C:\Users\Cohen Lab\Documents\GitHub\luminos\raffi_temp_data does not exist. Please modify init file with valid directory

>出错 Rig_Control_App (第 56 行)
            app.loadInitData(username);
出错 Simulator_App (第 7 行)
            app = app@Rig_Control_App('Simulator', varargin{:});

**Comment by rhotter** [comment]
Hi Luorong!

You'll have to edit the `dataDirectory` property in [`Simulation_App.json`](https://github.com/adamcohenlab/luminos-microscopy/blob/d72d2ea03c6ca3ea97096311c0c0c956061aad45/src/Applications/Simulator/Simulator.json#L3C3-L3C88). If you set the `dataDirectory` to a location on your computer where you want to store the data, you should be all set!

Raffi

**Comment by Luorong37** [comment]
great! I'll try it. see u tomorrow!



发件人："Raffi Hotter" ***@***.***>
发送日期：2024-04-16 14:36:15
收件人："adamcohenlab/luminos-microscopy" ***@***.***>
抄送人：Luorong37 ***@***.***>,Author ***@***.***>
主题：Re: [adamcohenlab/luminos-microscopy] Change user's name in Getting Started (Issue #3)


Hi Luorong!

You'll have to edit the dataDirectory property in Simulation_App.json. If you set the dataDirectory to a location on your computer where you want to store the data, you should be all set!

Raffi
